Repository FRONT-END-BOOTCAMP-PLUS-4/MoCha, pull requests merged in 2025-04, with the labels that each got.

#3 Header 생성
  app/(with-headaer)/layout.tsx
  app/components/shared/root-header/index.tsx
  app/globals.css
  app/layout.tsx
  package-lock.json
  package.json
Labels: ✨ FEAT

#5 chore: 파일 구조 변경
  app/(auth)/page.tsx
  app/(core)/challenge/page.tsx
  app/(core)/layout.tsx
  app/(core)/page.tsx
  app/(core)/user/page.tsx
  package-lock.json
  package.json
Labels: ⚙️ CHORE

#13 공통 Label, Input 컴포넌트 생성
  app/(auth)/login/page.tsx
  app/components/shared/input/Input.tsx
  app/components/shared/label/Label.tsx
  app/hooks/.gitkeep
  app/types/.gitkeep
  app/utils/.gitkeep
Labels: ✨ FEAT

#14 회원가입 페이지 UI 생성
  app/(auth)/layout.tsx
  app/(auth)/signup/page.tsx
  app/components/shared/input/Input.tsx
  app/components/shared/label/Label.tsx
  app/globals.css
  public/images/mocha_logo.svg
Labels: ✨ FEAT

#16 로그인 페이지 UI 생성
  app/(auth)/login/page.tsx
  public/images/social/google-logo.svg
  public/images/social/kakao-logo.svg
Labels: ✨ FEAT

#18 아이디 찾기 페이지 UI 생성
  app/(auth)/find-id/page.tsx
Labels: ✨ FEAT

#20 로그인, 회원가입 페이지 에러 메세지 추가
  app/(auth)/find-id/page.tsx
  app/(auth)/login/page.tsx
  app/(auth)/signup/page.tsx
  app/components/auth/ErrorMessage.tsx
  app/components/auth/LogoImage.tsx
  app/components/auth/Title.tsx
Labels: ✨ FEAT

#22 비밀번호 찾기 페이지 UI 생성
  app/(auth)/find-id/page.tsx
  app/(auth)/find-password/page.tsx
Labels: ✨ FEAT

#24 추가 정보 입력 페이지 UI 생성
  app/(auth)/social-info/page.tsx
Labels: ✨ FEAT

#25 메인 페이지 UI 구성
  app/(core)/page.tsx
  app/components/main/.gitkeep
  app/components/main/FloatingButton.tsx
  app/components/main/FullCalendarWrapper.tsx
  app/components/main/SummaryHeader.tsx
  app/types/.gitkeep
  app/types/Calendar.ts
  package-lock.json
  package.json
Labels: ✨ FEAT, 🎨 STYLE

#27 usePage Category ui 생성
  app/(auth)/find-id/page.tsx
  app/(auth)/find-password/page.tsx
  app/(auth)/login/page.tsx
  app/(auth)/signup/page.tsx
  app/(auth)/social-info/page.tsx
  app/(core)/layout.tsx
  app/(core)/user/page.tsx
  app/components/auth/.gitkeep
  app/components/main/FloatingButton.tsx
  app/components/main/FullCalendarWrapper.tsx
  app/components/main/SummaryHeader.tsx
  app/components/shared/.gitkeep
  app/components/user/.gitkeep
  app/components/user/CategoryChart.tsx
  app/components/user/CategoryList.tsx
  app/globals.css
  app/shared/hooks/.gitkeep
  app/shared/types/Calendar.ts
  app/shared/types/Category.ts
  app/shared/ui/input/Input.tsx
  app/shared/ui/label/Label.tsx
  app/shared/ui/root-header/index.tsx
  app/shared/ui/root-header/model/useNavModal.tsx
  app/shared/ui/root-header/ui/ButtonList.tsx
  app/shared/utils/cn.ts
  app/utils/.gitkeep
Labels: ✨ FEAT, ⚙️ CHORE, 🎨 STYLE

#30 auth 페이지 유효성 검사 임시 적용
  app/(auth)/find-id/page.tsx
  app/(auth)/find-password/page.tsx
  app/(auth)/layout.tsx
  app/(auth)/login/page.tsx
  app/(auth)/signup/page.tsx
  app/components/auth/ErrorMessage.tsx
  app/components/auth/MessageZone.tsx
  app/shared/ui/input/Input.tsx
  app/utils/validation.ts
Labels: ✨ FEAT, ⚙️ CHORE

#32 공용 버튼 제작
  app/shared/ui/button/Button.tsx
  package-lock.json
  package.json
Labels: ✨ FEAT

#34 수입/지출 입력 모달 제작
  app/(core)/page.tsx
  app/components/main/modal/IncomeExpenseForm.tsx
  app/components/main/modal/TransactionModal.tsx
  app/globals.css
  app/shared/types/Calendar.ts
Labels: ✨ FEAT, 🎨 STYLE

#35 refactor: type 분리
  app/components/main/modal/TransactionModal.tsx
  app/shared/types/Calendar.ts
Labels: ♻️ REFACTOR

#37 BarChart생성
  app/(core)/layout.tsx
  app/(core)/user/page.tsx
  app/components/user/CategoryChart.tsx
  app/components/user/CategoryList.tsx
  app/components/user/PeriodBarChart.tsx
  app/globals.css
  app/shared/types/Chart.ts
Labels: ✨ FEAT, 🎨 STYLE

#38 로그인, 회원가입 백엔드 아키텍처 로직
  app/(auth)/find-id/page.tsx
  app/(auth)/find-password/page.tsx
  app/(auth)/login/page.tsx
  app/(auth)/signup/page.tsx
  app/(auth)/social-info/page.tsx
  app/api/auth/check-nickname/route.ts
  app/api/auth/login/route.ts
  app/api/auth/logout/route.ts
  app/api/auth/me/route.ts
  app/api/auth/send-code/route.ts
  app/api/auth/signup/route.ts
  app/api/auth/verify-code/route.ts
  app/layout.tsx
  app/shared/lib/supabase.ts
  app/shared/stores/authStore.ts
  app/shared/ui/input/Input.tsx
  app/shared/ui/root-header/ui/ButtonList.tsx
  app/shared/utils/validation.ts
  application/auth/usecases/CheckNicknameUseCase.ts
  application/auth/usecases/GetUserByTokenUseCase.ts
  application/auth/usecases/LoginUseCase.ts
  application/auth/usecases/SendCodeUseCase.ts
  application/auth/usecases/SignupUseCase.ts
  application/auth/usecases/VerifyCodeUseCase.ts
  domain/auth/dto/LoginDto.ts
  domain/auth/dto/SignupDto.ts
  domain/auth/entities/User.ts
  domain/auth/repositories/UserRepository.ts
  domain/auth/services/EmailService.ts
  infra/auth/repositories/SupabaseUserRepository.ts
  infra/auth/services/NodemailerEmailService.ts
  infra/auth/utils/jwt.ts
  package-lock.json
  package.json
Labels: ✨ FEAT

#42 Auth 페이지 css 수정
  app/(auth)/find-id/page.tsx
  app/(auth)/find-password/page.tsx
  app/(auth)/layout.tsx
  app/(auth)/login/page.tsx
  app/(auth)/signup/page.tsx
  app/components/auth/Title.tsx
  app/shared/ui/button/Button.tsx
  app/shared/ui/input/Input.tsx
  app/shared/ui/label/Label.tsx
Labels: ✨ FEAT, 🎨 STYLE

#45 일자별 내역 목록 모달 구현
  app/(core)/page.tsx
  app/components/main/FloatingButton.tsx
  app/components/main/FullCalendarWrapper.tsx
  app/components/main/modal/DailyDetailModal.tsx
  app/components/main/modal/IncomeExpenseForm.tsx
  app/components/main/modal/TransactionItem.tsx
  app/shared/types/Calendar.ts
Labels: ✨ FEAT, 🎨 STYLE

#47 Profile 생성
  app/(core)/layout.tsx
  app/(core)/user/page.tsx
  app/components/user/ui/CategoryList.tsx
  app/components/user/ui/CategoryPieChart.tsx
  app/components/user/ui/PeriodBarChart.tsx
  app/components/user/ui/Profile.tsx
  app/components/user/widgets/ChartTab.tsx
  app/components/user/widgets/ProfileTab.tsx
  app/globals.css
  app/shared/consts/categoryColorMap.ts
  app/shared/types/Chart.ts
  app/shared/utils/cn.ts
  package-lock.json
  package.json
Labels: ✨ FEAT, ♻️ REFACTOR, 🎨 STYLE

#51 Feat:비밀번호 변경 UI생성
  app/(core)/user/page.tsx
  app/(core)/user/store/useFullModalStore.ts
  app/components/user/composite/ChartTab.tsx
  app/components/user/composite/FullScreenModal.tsx
  app/components/user/composite/SettingTab.tsx
  app/components/user/container/CategoryContainer.tsx
  app/components/user/container/PasswordChangeContainer.tsx
  app/components/user/container/PasswordContainer.tsx
  app/components/user/container/PeriodBarChartContainer.tsx
  app/components/user/container/ProfileSettingsContainer.tsx
  app/components/user/presentation/CategoryList.tsx
  app/components/user/presentation/CategoryPieChart.tsx
  app/components/user/presentation/PasswordChange.tsx
  app/components/user/presentation/PasswordCheck.tsx
  app/components/user/presentation/PeriodBarChart.tsx
  app/components/user/presentation/ProfileSettings.tsx
  app/components/user/ui/Profile.tsx
  app/components/user/widgets/ChartTab.tsx
  app/components/user/widgets/ProfileTab.tsx
  app/shared/types/Chart.ts
  app/shared/ui/root-header/index.tsx
Labels: ✨ FEAT, ♻️ REFACTOR, ✍🏻 RENAME, 🎨 STYLE

#52 feat: 구글, 카카오 소셜 로그인 로직 구현
  app/(auth)/find-id/page.tsx
  app/(auth)/login/page.tsx
  app/(auth)/reset-password/page.tsx
  app/(auth)/signup/page.tsx
  app/(auth)/social-callback/[provider]/page.tsx
  app/(auth)/social-info/page.tsx
  app/api/auth/[provider]/exchange/route.ts
  app/api/auth/[provider]/redirect/route.ts
  app/api/auth/logout/route.ts
  app/api/user/route.ts
  app/shared/consts/errorMessages.ts
  app/shared/consts/validation.ts
  app/shared/ui/root-header/ui/ButtonList.tsx
  application/auth/dto/SocialLoginDto.ts
  application/auth/usecase/SendCodeUseCase.ts
  application/auth/usecase/SocialLoginUseCase.ts
  domain/user/entities/User.ts
  domain/user/repositories/ProviderRepository.ts
  domain/user/repositories/UserRepository.ts
  domain/user/services/OAuthService.ts
  infra/oauth/GoogleOAuthService.ts
  infra/oauth/KakaoOAuthService.ts
  infra/oauth/OAuthServiceFactory.ts
  infra/user/repositories/SupabaseProviderRepository.ts
  infra/user/repositories/SupabaseUserRepository.ts
Labels: ✨ FEAT, ⚙️ CHORE, ⛔️ REMOVE

#58 Chore: clean architecture 구조변경
  app/api/auth/[provider]/exchange/route.ts
  app/api/auth/check-nickname/route.ts
  app/api/auth/find-id/route.ts
  app/api/auth/login/route.ts
  app/api/auth/reset-password/route.ts
  app/api/auth/send-code/reset-password/route.ts
  app/api/auth/send-code/route.ts
  app/api/auth/verify-code/route.ts
  app/api/user/route.ts
  app/components/user/container/ProfileSettingsContainer.tsx
  app/components/user/presentation/PasswordChange.tsx
  app/components/user/presentation/PasswordCheck.tsx
  application/usecases/auth/CheckNicknameUseCase.ts
  application/usecases/auth/FindEmailUseCase.ts
  application/usecases/auth/LoginUseCase.ts
  application/usecases/auth/ResetPasswordUseCase.ts
  application/usecases/auth/SendCodeUseCase.ts
  application/usecases/auth/SocialLoginUseCase.ts
  application/usecases/auth/VerifyCodeUseCase.ts
  application/usecases/auth/dto/CheckNicknameDto .ts
  application/usecases/auth/dto/FindEmailDto.ts
  application/usecases/auth/dto/LoginDto.ts
  application/usecases/auth/dto/ResetPasswordDto.ts
  application/usecases/auth/dto/SendCodeDto.ts
  application/usecases/auth/dto/SocialLoginDto.ts
  application/usecases/auth/dto/VerifyCodeDto.ts
  application/usecases/user/GetUserUseCase.ts
  application/usecases/user/SignupUsecase.ts
  application/usecases/user/dto/SignupDto.ts
  domain/entities/User.ts
  domain/repositories/ProviderRepository.ts
  domain/repositories/UserRepository.ts
  domain/services/OAuthService.ts
  infra/oauth/GoogleOAuthService.ts
  infra/oauth/KakaoOAuthService.ts
  infra/oauth/OAuthServiceFactory.ts
  infra/repositories/supabase/SupabaseProviderRepository.ts
  infra/repositories/supabase/SupabaseUserRepository.ts
  infra/utils/email.ts
  infra/utils/jwt.ts
Labels: ⚙️ CHORE

#60 rename: shared ui 파일 이름 통일
  app/(auth)/find-id/page.tsx
  app/(auth)/login/page.tsx
  app/(auth)/reset-password/page.tsx
  app/(auth)/signup/page.tsx
  app/(auth)/social-info/page.tsx
  app/(core)/user/page.tsx
  app/components/main/modal/IncomeExpenseForm.tsx
  app/components/user/presentation/PasswordChange.tsx
  app/components/user/presentation/PasswordCheck.tsx
  app/components/user/presentation/ProfileSettings.tsx
  app/shared/ui/button/index.tsx
  app/shared/ui/input/index.tsx
  app/shared/ui/label/index.tsx
Labels: ✍🏻 RENAME

#62 refactor: 날짜 formatted 함수 분리
  app/components/main/FullCalendarWrapper.tsx
  app/shared/utils/formattedDate.ts
Labels: ♻️ REFACTOR

#64 공통 비밀번호 input 생성
  app/(auth)/find-id/page.tsx
  app/(auth)/login/page.tsx
  app/(auth)/reset-password/page.tsx
  app/(auth)/signup/page.tsx
  app/(auth)/social-info/page.tsx
  app/components/auth/LogoImage.tsx
  app/shared/hooks/useIsHide.ts
  app/shared/ui/input/PasswordInput.tsx
  app/shared/ui/input/index.tsx
  infra/repositories/supabase/SupabaseProviderRepository.ts
Labels: ✨ FEAT, ⚙️ CHORE, ♻️ REFACTOR

#67 Transaction API 임시생성
  app/(core)/layout.tsx
  app/(core)/page.tsx
  app/api/route.ts
  app/api/temp/route.ts
  app/components/user/container/PeriodBarChartContainer.tsx
  app/layout.tsx
  application/usecases/transactions/MonthlySummaryUsecase.ts
  application/usecases/transactions/dto/MonthlySummaryDto.ts
  domain/entities/Category.ts
  domain/entities/Transaction.ts
  domain/repositories/TransactionRepo.ts
  domain/repositories/UserRepository.ts
  infra/repositories/supabase/SbTransactionRepo.ts
Labels: ✨ FEAT

#72 feat: Category API 생성
  app/api/category/route.ts
  app/components/user/container/CategoryContainer.tsx
  application/usecases/category/GETmonthlyCategoryUsecase.ts
  domain/entities/Transaction.ts
  domain/repositories/CategoryRepo.ts
  domain/repositories/TransactionRepo.ts
  infra/repositories/supabase/SbCategoryRepo.ts
Labels: ✨ FEAT, ♻️ REFACTOR

#73 refator: 백엔드 에러처리 타입 수정
  app/(auth)/login/page.tsx
  app/(auth)/social-callback/[provider]/page.tsx
  app/api/auth/[provider]/exchange/route.ts
  app/api/auth/[provider]/redirect/route.ts
  app/api/auth/find-id/route.ts
  app/api/auth/login/route.ts
  app/api/auth/reset-password/route.ts
  app/api/auth/send-code/reset-password/route.ts
  app/api/auth/send-code/route.ts
  app/api/auth/verify-code/route.ts
  app/api/user/route.ts
  app/shared/stores/authStore.ts
  application/usecases/auth/SocialLoginUseCase.ts
  application/usecases/auth/dto/SocialLoginDto.ts
  domain/repositories/ProviderRepository.ts
  domain/repositories/UserRepo.ts
  infra/oauth/GoogleOAuthService.ts
  infra/oauth/KakaoOAuthService.ts
  infra/repositories/supabase/SbUserRepo.ts
  infra/repositories/supabase/SupabaseProviderRepository.ts
  infra/utils/jwt.ts
Labels: ♻️ REFACTOR

#75 feat: 메인 페이지 api 연결
  app/(core)/page.tsx
  app/api/transactions/daily/route.ts
  app/api/transactions/monthly/route.ts
  app/components/main/FullCalendarWrapper.tsx
  app/components/main/SummaryHeader.tsx
  app/shared/types/Calendar.ts
  application/usecases/transactions/GetDailySummaryUsecase.ts
  application/usecases/transactions/GetMonthlySummaryUsecase.ts
  application/usecases/transactions/dto/DailySummaryDto.ts
  application/usecases/transactions/dto/MonthlySummaryDto.ts
  domain/entities/Transaction.ts
  domain/repositories/TransactionRepo.ts
  infra/repositories/supabase/SbTransactionRepo.ts
Labels: ✨ FEAT

#76 feat: User entity 수정
  app/(auth)/signup/page.tsx
  app/api/transactions/monthly/route.ts
  application/usecases/auth/LoginUseCase.ts
  domain/entities/User.ts
  infra/repositories/supabase/SbTransactionRepo.ts
  infra/utils/jwt.ts
Labels: ✨ FEAT

#80 refactor: 소셜 로그인 수정
  app/(auth)/kakao-callback/page.tsx
  app/(auth)/login/page.tsx
  app/api/auth/[provider]/exchange/route.ts
  app/api/auth/[provider]/redirect/route.ts
  app/api/auth/google/route.ts
  app/api/auth/kakao/exchange/route.ts
  app/api/auth/kakao/redirect/route.ts
  app/components/auth/GoogleLoginButton.tsx
  app/components/auth/KakaoLoginButton.tsx
  app/layout.tsx
  app/shared/stores/authStore.ts
  application/usecases/auth/GoogleLoginUseCase.ts
  application/usecases/auth/KakaoLoginUseCase.ts
  application/usecases/auth/dto/SocialLoginDto.ts
  application/usecases/user/SignupUsecase.ts
  application/usecases/user/dto/SignupDto.ts
  domain/entities/User.ts
  domain/repositories/UserRepo.ts
  domain/services/OAuthService.ts
  infra/oauth/GoogleOAuthService.ts
  infra/oauth/KakaoOAuthService.ts
  infra/oauth/OAuthServiceFactory.ts
  infra/repositories/supabase/SbUserRepo.ts
  package-lock.json
  package.json
Labels: ✨ FEAT, ⚙️ CHORE, ⛔️ REMOVE, ♻️ REFACTOR

#82 feat: 버튼 로딩 적용, 로그인 시, 로그인/회원가입 페이지 접근 차단
  app/(auth)/find-id/page.tsx
  app/(auth)/layout.tsx
  app/(auth)/login/page.tsx
  app/(auth)/reset-password/page.tsx
  app/(auth)/signup/page.tsx
  app/api/auth/send-code/reset-password/route.ts
  app/components/auth/AuthProvider.tsx
  app/components/auth/GoogleLoginButton.tsx
  app/components/auth/KakaoLoginButton.tsx
  app/layout.tsx
  app/shared/ui/button/index.tsx
  app/shared/ui/input/PasswordInput.tsx
  app/shared/ui/input/index.tsx
  application/usecases/user/GetUserUseCase.ts
  application/usecases/user/dto/UserProfileDto.ts
Labels: ✨ FEAT, ♻️ REFACTOR

#83 feat: Category API 생성
  app/(core)/layout.tsx
  app/api/category/route.ts
  app/api/temp/route.ts
  app/components/user/composite/ChartTab.tsx
  app/components/user/container/CategoryContainer.tsx
  app/components/user/presentation/Category.tsx
  app/components/user/presentation/CategoryList.tsx
  app/components/user/presentation/CategoryPieChart.tsx
  application/usecases/category/GETmonthlyCategoryUsecase.ts
  application/usecases/category/dto/MonthlyCategoryDto.ts
  domain/repositories/CategoryRepo.ts
  infra/repositories/supabase/SbCategoryRepo.ts
Labels: ✨ FEAT, ♻️ REFACTOR, 🎨 STYLE

#87 feat: refresh_token으로 만료된 access_token 재발급
  app/(auth)/kakao-callback/page.tsx
  app/(auth)/login/page.tsx
  app/api/auth/google/route.ts
  app/api/auth/kakao/exchange/route.ts
  app/api/auth/login/route.ts
  app/api/auth/refresh/route.ts
  app/components/auth/AuthProvider.tsx
  app/components/auth/GoogleLoginButton.tsx
  app/shared/utils/refreshToken.ts
  application/usecases/auth/GoogleLoginUseCase.ts
  application/usecases/auth/KakaoLoginUseCase.ts
  application/usecases/auth/LoginUseCase.ts
  application/usecases/user/SignupUsecase.ts
  infra/oauth/KakaoOAuthService.ts
  infra/repositories/supabase/SbUserRepo.ts
  infra/utils/jwt.ts
Labels: ✨ FEAT, ♻️ REFACTOR

#90 Feat/84
  app/(core)/layout.tsx
  app/api/category/route.ts
  app/api/transactions/monthly/route.ts
  app/components/user/composite/ChartTab.tsx
  app/components/user/container/CategoryContainer.tsx
  app/components/user/container/PeriodBarChartContainer.tsx
  app/components/user/presentation/PeriodBarChart.tsx
  app/shared/types/Chart.ts
  application/usecases/category/GETmonthlyCategoryUsecase.ts
  application/usecases/category/dto/MonthlyCategoryDto.ts
  application/usecases/transactions/GetMonthlySummaryUsecase.ts
  application/usecases/transactions/dto/MonthlySummaryDto.ts
  domain/repositories/CategoryRepo.ts
  domain/repositories/TransactionRepo.ts
  infra/repositories/supabase/SbCategoryRepo.ts
  infra/repositories/supabase/SbTransactionRepo.ts
Labels: ✨ FEAT, ♻️ REFACTOR, 🎨 STYLE

#94 Refactor: api fetch 방식 수정
  app/(core)/page.tsx
Labels: ♻️ REFACTOR

#92 rename: 카카오 로그인 api 경로 수정
  app/(auth)/kakao-callback/page.tsx
  app/(auth)/layout.tsx
  app/api/auth/kakao/redirect/route.ts
  app/api/auth/kakao/route.ts
  app/components/auth/AuthProvider.tsx
  app/components/auth/KakaoLoginButton.tsx
Labels: ♻️ REFACTOR, ✍🏻 RENAME

#97 feat: 로그인 여부에 따른 ui 변경
  app/(auth)/layout.tsx
  app/components/auth/AuthProvider.tsx
  app/components/auth/LogoImage.tsx
  app/favicon.ico
  app/shared/ui/root-header/index.tsx
  app/shared/ui/root-header/ui/ButtonList.tsx
  public/images/mocha-logo.png
Labels: ✨ FEAT, 🎨 STYLE

#98 유저프로필 수정 API
  app/api/category/chart/route.ts
  app/api/user/edit/route.ts
  app/components/user/container/CategoryContainer.tsx
  app/components/user/container/PeriodBarChartContainer.tsx
  app/components/user/container/ProfileSettingsContainer.tsx
  app/components/user/presentation/PasswordChange.tsx
  app/components/user/presentation/PeriodBarChart.tsx
  app/components/user/presentation/ProfileSettings.tsx
  application/usecases/user/PutUserInfoUseCase.ts
  domain/error.ts
  domain/repositories/UserRepo.ts
  infra/repositories/supabase/SbUserRepo.ts
Labels: ✨ FEAT, ♻️ REFACTOR, 🎨 STYLE, 💬 COMMENT

#100 feat: 항목 추가 기능 구현
  app/(core)/page.tsx
  app/api/category/chart/route.ts
  app/api/category/route.ts
  app/api/transactions/route.ts
  app/components/main/FullCalendarWrapper.tsx
  app/components/main/modal/IncomeExpenseForm.tsx
  application/usecases/category/GETcategoryUsecase.ts
  application/usecases/category/dto/CategoryDto.ts
  application/usecases/transactions/PostTransactionUsecase.ts
  application/usecases/transactions/dto/TransactionsDto.ts
  domain/repositories/CategoryRepo.ts
  domain/repositories/TransactionRepo.ts
  infra/repositories/supabase/SbCategoryRepo.ts
  infra/repositories/supabase/SbTransactionRepo.ts
Labels: ✨ FEAT

#102 비밀번호 변경 API 생성
  app/api/user/password/route.ts
  app/components/user/container/PasswordChangeContainer.tsx
  app/components/user/container/PasswordContainer.tsx
  app/components/user/presentation/PasswordChange.tsx
  app/components/user/presentation/PasswordCheck.tsx
  application/usecases/user/ChangePasswordUsecase.ts
  application/usecases/user/MatchPasswordUsecase.ts
Labels: ✨ FEAT, 🎨 STYLE

#103 feat: 항목 삭제 기능 구현
  app/api/transactions/route.ts
  app/components/main/FullCalendarWrapper.tsx
  app/components/main/modal/DailyDetailModal.tsx
  app/components/main/modal/TransactionItem.tsx
  application/usecases/transactions/DeleteTransactionUsecase.ts
  domain/repositories/TransactionRepo.ts
  infra/repositories/supabase/SbTransactionRepo.ts
Labels: ✨ FEAT

#106 feat: 데이터 패칭 로직 수정
  app/(core)/page.tsx
  app/components/main/FullCalendarWrapper.tsx
  app/shared/ui/root-header/ui/ButtonList.tsx
Labels: ✨ FEAT

#108 Feat: 회원탈퇴 API
  app/api/user/delete/route.ts
  app/api/user/edit/route.ts
  app/components/user/composite/SettingTab.tsx
  domain/repositories/UserRepo.ts
  infra/repositories/supabase/SbUserRepo.ts
Labels: ✨ FEAT

#109 Feat: userPage 경로처리
  app/(core)/user/page.tsx
Labels: ✨ FEAT
